# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-01 23:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20181001_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='post',
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='social.Post'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='social.User'),
            preserve_default=False,
        ),
    ]
